# Generated by Django 4.1 on 2025-12-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barrier', '0003_remove_barrier_cars_remove_barrierhistory_car_and_more'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
