# Generated by Django 4.1 on 2025-12-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('barrier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='cars',
            field=models.ManyToManyField(blank=True, to='car.car'),
        ),
    ]
