# Generated by Django 4.1 on 2025-12-25 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barrier', '0002_barrier_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrier',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='barrierhistory',
            name='car',
        ),
        migrations.AddField(
            model_name='barrierhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
