# Generated by Django 4.1 on 2025-12-25 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barrier', '0003_remove_barrier_cars_remove_barrierhistory_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
